//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMEf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CrmDomain;
    
    public partial class AutoCribCrmConncetion : DbContext
    {
        public AutoCribCrmConncetion()
            : base("name=AutoCribCrmConncetion")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountDB> AccountDBs { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ASPeLog> ASPeLogs { get; set; }
        public virtual DbSet<ASPevent> ASPevents { get; set; }
        public virtual DbSet<auditMyTran> auditMyTrans { get; set; }
        public virtual DbSet<auditOutbox> auditOutboxes { get; set; }
        public virtual DbSet<AutoPO> AutoPOes { get; set; }
        public virtual DbSet<AutoPOEvent> AutoPOEvents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CribAccess> CribAccesses { get; set; }
        public virtual DbSet<CriticalBinEvent> CriticalBinEvents { get; set; }
        public virtual DbSet<CriticalBin> CriticalBins { get; set; }
        public virtual DbSet<CurOnHandBurn> CurOnHandBurns { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Databas> Databases { get; set; }
        public virtual DbSet<DBOevent> DBOevents { get; set; }
        public virtual DbSet<EquipmentNumber> EquipmentNumbers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportAuth> ReportAuths { get; set; }
        public virtual DbSet<ReportGroupAccount> ReportGroupAccounts { get; set; }
        public virtual DbSet<ReportLog> ReportLogs { get; set; }
        public virtual DbSet<ReportPermission> ReportPermissions { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TempCriticalBin> TempCriticalBins { get; set; }
        public virtual DbSet<TempCriticalBin2> TempCriticalBin2 { get; set; }
        public virtual DbSet<TempReport> TempReports { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<AutoPOTemp> AutoPOTemps { get; set; }
        public virtual DbSet<ReportGroup> ReportGroups { get; set; }
        public virtual DbSet<ReportPermissionType> ReportPermissionTypes { get; set; }
        public virtual DbSet<SyncTable> SyncTables { get; set; }
    }
}
