//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public string HostedBy { get; set; }
        public string ClientID { get; set; }
        public short AccountType { get; set; }
        public string VendorID { get; set; }
        public string FolderPath { get; set; }
        public string Company { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SecureLevel { get; set; }
        public Nullable<int> Licensed { get; set; }
        public Nullable<int> Active { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email2 { get; set; }
        public string Fax { get; set; }
        public string Memo { get; set; }
        public string Logo { get; set; }
        public string WebsiteURL { get; set; }
        public string CCNumber { get; set; }
        public string CCType { get; set; }
        public string CCExpMonth { get; set; }
        public string CCExpDay { get; set; }
        public string CCExpYear { get; set; }
        public string NameOnCard { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string PasswordHintQuestion { get; set; }
        public string PasswordHint { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> UseAutoCribClient { get; set; }
        public Nullable<System.DateTime> SupportBeginDate { get; set; }
        public Nullable<System.DateTime> SupportEndDate { get; set; }
        public Nullable<int> Subscription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NumOfMachines { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public bool Dashboard { get; set; }
        public string GroupId { get; set; }
        public string IntelliviewPassword { get; set; }
        public Nullable<bool> IntelliviewAdmin { get; set; }
        public bool RestrictedAdmin { get; set; }
    }
}
