//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPeLog
    {
        public int id { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EventName { get; set; }
        public string RunBy { get; set; }
        public Nullable<System.DateTime> ThisRunDate { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public string Status { get; set; }
        public string StatusInfo { get; set; }
        public string Data { get; set; }
    }
}
