//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPevent
    {
        public int id { get; set; }
        public Nullable<int> DbID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string MyGroup { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string EventDesc { get; set; }
        public Nullable<int> isOn { get; set; }
        public Nullable<int> Freq { get; set; }
        public Nullable<int> Every { get; set; }
        public Nullable<System.DateTime> NextRunOn { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DeleteEvent { get; set; }
        public string NotifyAddr { get; set; }
        public string NotifySubject { get; set; }
        public Nullable<int> EXE { get; set; }
        public Nullable<int> ExeExitTime { get; set; }
        public string WebPageURL { get; set; }
        public Nullable<int> Sun { get; set; }
        public Nullable<int> Mon { get; set; }
        public Nullable<int> Tue { get; set; }
        public Nullable<int> Wed { get; set; }
        public Nullable<int> Thr { get; set; }
        public Nullable<int> Fri { get; set; }
        public Nullable<int> Sat { get; set; }
        public string LastRunStatus { get; set; }
        public Nullable<int> SuccRuns { get; set; }
        public Nullable<int> FailedRuns { get; set; }
        public Nullable<int> TimeOffSet { get; set; }
        public bool Daily { get; set; }
        public bool Weekly { get; set; }
        public bool Monthly { get; set; }
        public bool SelectDay { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<int> DayofWeek { get; set; }
        public Nullable<int> DayofMonth { get; set; }
        public string TimeZone { get; set; }
    }
}
