//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditOutbox
    {
        public int RecordID { get; set; }
        public string DbName { get; set; }
        public string AuditType { get; set; }
        public Nullable<int> OutboxRecID { get; set; }
        public string ID { get; set; }
        public string Contact { get; set; }
        public string TableName { get; set; }
        public string Type { get; set; }
        public string Key1 { get; set; }
        public string Key2 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string ComputerName { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
