//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditMyTran
    {
        public int RecordID { get; set; }
        public string DbName { get; set; }
        public string AuditType { get; set; }
        public Nullable<int> MyTranRecID { get; set; }
        public Nullable<System.DateTime> MyDate { get; set; }
        public Nullable<System.DateTime> MyTime { get; set; }
        public string Station { get; set; }
        public string Bin { get; set; }
        public string Type { get; set; }
        public string Item { get; set; }
        public int Quantity { get; set; }
        public string Emp { get; set; }
        public int BurnQty { get; set; }
        public int CurOnHand { get; set; }
        public int CurBurn { get; set; }
        public int CurOnHand2 { get; set; }
        public int CurBurn2 { get; set; }
        public int AdjQty { get; set; }
    }
}
