//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPO
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> MyDate { get; set; }
        public Nullable<System.DateTime> MyTime { get; set; }
        public Nullable<int> DbID { get; set; }
        public string DbName { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> POTime { get; set; }
        public Nullable<bool> GeneratePO { get; set; }
        public Nullable<bool> GenerateRoboPO { get; set; }
        public Nullable<bool> ExportPO { get; set; }
        public string PoNo { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> POSent { get; set; }
        public Nullable<bool> EmailOn { get; set; }
        public string Crib { get; set; }
        public Nullable<bool> cXML { get; set; }
        public Nullable<bool> cXMLSent { get; set; }
        public Nullable<bool> cXMLCreated { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<bool> Run { get; set; }
        public Nullable<bool> Approval { get; set; }
    }
}
