//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurOnHandBurn
    {
        public int RecordID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> TranNo { get; set; }
        public Nullable<System.DateTime> MyDate { get; set; }
        public Nullable<System.DateTime> MyTime { get; set; }
        public string Station { get; set; }
        public string Bin { get; set; }
        public string Item { get; set; }
        public string Type { get; set; }
        public string Emp { get; set; }
        public Nullable<int> CurOnHand { get; set; }
        public Nullable<int> CurOnHand2 { get; set; }
        public Nullable<int> CurBurn { get; set; }
        public Nullable<int> CurBurn2 { get; set; }
        public string DbName { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
    }
}
