//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int ID { get; set; }
        public string Alpha2Code { get; set; }
        public string CurrencyCodeA { get; set; }
        public string CurrencyCodeN { get; set; }
        public Nullable<int> MinorUnit { get; set; }
        public string CurrencyName { get; set; }
        public string note { get; set; }
    }
}
