//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> DbID { get; set; }
        public string Company { get; set; }
        public Nullable<bool> MultiSearch { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
