//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentNumber
    {
        public string Crib { get; set; }
        public int DbID { get; set; }
        public int ParentID { get; set; }
        public string EquipmentNo { get; set; }
    }
}
