//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int fldAuto { get; set; }
        public string fldUserID { get; set; }
        public string fldCompany { get; set; }
        public string fldDescription { get; set; }
        public string fldEmail { get; set; }
        public Nullable<System.DateTime> fldTimeIn { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public string IPAddress { get; set; }
    }
}
