//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAuth
    {
        public System.Guid token { get; set; }
        public System.DateTime createdDate { get; set; }
        public int accountID { get; set; }
        public string ipAddress { get; set; }
    }
}
