//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int DbID { get; set; }
        public string Station1 { get; set; }
        public bool Active { get; set; }
        public int Type { get; set; }
        public string RoboType { get; set; }
        public string KeyItemCode { get; set; }
        public Nullable<System.DateTime> LastIssue { get; set; }
        public Nullable<int> NumofBins { get; set; }
        public Nullable<int> LockControl { get; set; }
    }
}
