//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCriticalBin
    {
        public int RecordID { get; set; }
        public string Station { get; set; }
        public string MyNo { get; set; }
        public string Item { get; set; }
        public string Description1 { get; set; }
        public Nullable<int> PackQty { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<int> ExtendedQty { get; set; }
        public string Vendor { get; set; }
        public string Email { get; set; }
        public string DatabaseName { get; set; }
        public string Company { get; set; }
    }
}
