//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCriticalBin2
    {
        public int RecordID { get; set; }
        public Nullable<int> DbID { get; set; }
        public string DbName { get; set; }
        public string Company { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public string AppVersion { get; set; }
        public System.DateTime MyDateTime { get; set; }
    }
}
